'use strict';
const C=window.Contest,people=C.people,milestones=C.milestones,days=Array.from({length:24},(_,i)=>i+7),depts=[...new Set(people.map(p=>p.dept))];
const $=id=>document.getElementById(id),rub=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₽',esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let state=C.cached(),published=C.cached(),editing=false,view='assigned',query='',dept='all',startDay=7,endDay=innerWidth<1500?13:30,baseAt=published.updatedAt,pendingImport=null,undoState=null,selectedPerson=null,hasDraft=false,loadError=false;
try{const draft=JSON.parse(localStorage.getItem(C.draftKey));if(draft){state=C.normalize(draft.state);baseAt=draft.baseAt;hasDraft=true;}else{const old=JSON.parse(localStorage.getItem('golden-meetings-september-7-30-2026-v1'));if(old){state=C.normalize(old,{legacy:true});hasDraft=true;}}}catch(e){hasDraft=true;loadError=true;}
const reward=C.reward,nextReward=C.next,dayBonus=a=>a.reduce((s,n)=>s+Math.max(0,n-3)*1000,0),level=n=>n>=4?4:n,weekday=day=>['вс','пн','вт','ср','чт','пт','сб'][new Date(2026,8,day).getDay()];
function filtered(){return people.filter(p=>(dept==='all'||p.dept===dept)&&(!query||p.name.toLowerCase().includes(query.toLowerCase())));}
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),5000);}
function updateStats(){const s=C.summary(state);$('statPeople').textContent=people.length;$('statAssigned').textContent=s.assigned;$('statHeld').textContent=s.held;$('statMoney').textContent=rub(s.money);}
function draftStatus(){if(loadError){$('draftStatus').textContent='Черновик не прочитан и оставлен без изменений. Импортируйте резервную копию или возьмите данные с сайта.';$('draftStatus').classList.add('pending');return;}const dirty=C.signature(state)!==C.signature(published);$('draftStatus').textContent=dirty?'Есть изменения только на этом устройстве. Опубликуйте их для ТВ.':'Показана опубликованная версия';$('draftStatus').classList.toggle('pending',dirty);$('updatedAt').textContent=state.updatedAt?'Данные: '+new Date(state.updatedAt).toLocaleString('ru-RU',{timeZone:'Europe/Moscow',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})+' МСК':'Результатов пока нет';const n=Object.values(state.unverifiedHeld).reduce((a,b)=>a+b,0);$('legacyNote').hidden=!n;$('legacyNote').textContent=n?'В старой версии '+n+' проведённых без дат. Они сохранены в итогах. Перед публикацией распределите их по встречам через карточки сотрудников.':'';}
function persist(){if(loadError)throw Error('Сначала восстановите данные из резервной копии');state=C.normalize({...state,updatedAt:new Date().toISOString()});hasDraft=true;try{localStorage.setItem(C.draftKey,JSON.stringify({state,baseAt}));}catch{toast('Не удалось сохранить на устройстве. Скачайте резервную копию.');}updateStats();draftStatus();}
function checkpoint(){undoState=JSON.parse(JSON.stringify(state));$('undoBtn').disabled=false;}
function renderAssigned(){
 const list=filtered(),visibleDays=days.filter(d=>d>=startDay&&d<=endDay);let html='<table><thead><tr><th class="name-col">Сотрудник</th>';
 for(const d of visibleDays){const w=weekday(d);html+=`<th class="day-head ${w==='сб'||w==='вс'?'weekend':''}"><b>${d}</b><small>${w}</small></th>`;}
 html+='<th class="summary-col">Всего за конкурс</th><th class="summary-col">Золотых дней</th><th class="money-col">Начислено</th></tr></thead><tbody>';
 let last='';for(const p of list){if(p.dept!==last){last=p.dept;html+=`<tr class="group-row"><td colspan="${visibleDays.length+4}">${esc(last)}</td></tr>`;}const a=state.assigned[p.id];html+=`<tr data-row="${p.id}"><td class="name-col"><b>${esc(p.name)}</b><small>${esc(p.role)}</small></td>`;for(const d of visibleDays){const n=a[d-1];html+=`<td class="day-cell lv${level(n)}"><input class="day-input" type="number" min="0" max="100000" step="1" value="${n}" data-id="${p.id}" data-day="${d-1}" ${editing?'':'disabled'} aria-label="${esc(p.name)}, ${d} сентября"></td>`;}html+=`<td class="summary-col"><b>${C.total(a)}</b></td><td class="summary-col"><b>${a.slice(6).filter(n=>n>=3).length}</b></td><td class="money-col"><b>${rub(C.bonus(a))}</b></td></tr>`;}
 $('assignedView').innerHTML=list.length?html+'</tbody></table>':'<p class="empty">Сотрудники не найдены</p>';
}
function renderHeld(){let last='',html='';for(const p of filtered()){if(p.dept!==last){last=p.dept;html+=`<div class="held-group">${esc(last)}</div>`;}const n=state.held[p.id],earned=reward(n),next=nextReward(n);html+=`<div class="held-row"><div class="person"><b>${esc(p.name)}</b><small>${esc(p.role)}</small><button class="btn journal-btn" data-person="${p.id}">${editing?'Добавить / журнал':'Журнал встреч'}</button></div><div class="held-fact"><b>${n}</b><small>проведено</small>${state.unverifiedHeld[p.id]?'<small class="pending">есть без дат</small>':''}</div><div class="track-wrap"><div class="track"><div class="fill" style="width:${C.progress(n)}%"></div><div class="nodes">${milestones.map((m,i)=>`<div class="node ${n>=m.n?'reached':''}" style="left:${(i+1)/8*100}%">${m.n}<span>${m.p/1000}к</span></div>`).join('')}</div></div></div><div class="next-box"><span>${next?'До следующей премии':'Все ступени пройдены'}</span><b>${next?'Ещё '+(next.n-n)+' · +'+rub(next.p-earned):'Максимальная награда'}</b></div><div class="earned"><span>Начислено всего</span><b>${rub(earned)}</b></div></div>`;}$('heldView').innerHTML=html||'<p class="empty">Сотрудники не найдены</p>';}
function render(){if(view==='assigned')renderAssigned();else renderHeld();$('assignedView').hidden=view!=='assigned';$('heldView').hidden=view!=='held';$('calendarRange').hidden=view!=='assigned';document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('boardTitle').textContent=view==='assigned'?'Назначения по дате назначения':'Проведённые за 7–30 сентября';$('boardSubtitle').textContent=view==='assigned'?'Итоги справа всегда за весь конкурс':'Одна итоговая награда за достигнутую ступень';$('editBtn').textContent=editing?'Завершить ввод':'Ввести результаты';updateStats();draftStatus();}
function download(data,name){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function openJournal(id){selectedPerson=id;const p=people.find(p=>p.id===id);$('journalTitle').textContent=p.name;$('eventForm').hidden=!editing;$('eventIds').value='';$('eventDate').value=new Date().toLocaleDateString('sv-SE',{timeZone:'Europe/Moscow'});if($('eventDate').value<C.period.start||$('eventDate').value>C.period.end)$('eventDate').value=C.period.start;renderJournal();$('journalDialog').showModal();}
function renderJournal(){const entries=state.heldEvents.filter(e=>e.personId===selectedPerson).sort((a,b)=>a.date.localeCompare(b.date));$('journalEntries').innerHTML=entries.length?entries.map(e=>`<div class="event-row"><span>${e.date.split('-').reverse().join('.')}</span><span>Запись ${e.id.slice(0,8)}</span>${editing?`<button class="btn" data-remove="${e.id}">Убрать</button>`:''}</div>`).join(''):'<p>Датированных встреч пока нет.</p>';$('legacyCount').textContent=state.unverifiedHeld[selectedPerson]||0;$('legacyBox').hidden=!(state.unverifiedHeld[selectedPerson]>0);$('replaceLegacy').checked=!!state.unverifiedHeld[selectedPerson];$('journalError').textContent='';}
$('deptFilter').innerHTML+=[...depts].map(d=>`<option value="${esc(d)}">${esc(d)}</option>`).join('');
document.querySelector('.tabs').onclick=e=>{const b=e.target.closest('.tab');if(b){view=b.dataset.view;render();}};
$('search').oninput=e=>{query=e.target.value;clearTimeout(window.searchTimer);window.searchTimer=setTimeout(render,120);};
$('deptFilter').onchange=e=>{dept=e.target.value;render();};
$('calendarRange').value=startDay+':'+endDay;
$('calendarRange').onchange=e=>{[startDay,endDay]=e.target.value.split(':').map(Number);renderAssigned();};
$('editBtn').onclick=()=>{if(loadError){toast('Сначала восстановите данные из резервной копии');return;}editing=!editing;render();};
$('assignedView').addEventListener('change',e=>{const input=e.target;if(!input.matches('.day-input')||!editing)return;const id=input.dataset.id,day=Number(input.dataset.day);try{const n=C.count(Number(input.value));checkpoint();state.assigned[id][day]=n;persist();input.parentElement.className='day-cell lv'+level(n);const tr=input.closest('tr');tr.querySelectorAll('.summary-col b')[0].textContent=C.total(state.assigned[id]);tr.querySelectorAll('.summary-col b')[1].textContent=state.assigned[id].slice(6).filter(n=>n>=3).length;tr.querySelector('.money-col b').textContent=rub(C.bonus(state.assigned[id]));}catch(err){input.value=state.assigned[id][day];toast(err.message);}});
$('heldView').onclick=e=>{const b=e.target.closest('[data-person]');if(b)openJournal(b.dataset.person);};
$('eventForm').onsubmit=async e=>{e.preventDefault();const button=$('addEventBtn');button.disabled=true;try{const date=$('eventDate').value,refs=$('eventIds').value.split('\n').map(v=>v.trim()).filter(Boolean);if(!refs.length)throw Error('Введите ID хотя бы одной встречи');if(refs.some(s=>s.length>200))throw Error('ID встречи слишком длинный');const records=[];for(const ref of refs){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(C.contestId+':'+ref.toLowerCase()));records.push({id:Array.from(new Uint8Array(bytes),n=>n.toString(16).padStart(2,'0')).join(''),personId:selectedPerson,date});}const next=JSON.parse(JSON.stringify(state));next.heldEvents.push(...records);if($('replaceLegacy').checked)next.unverifiedHeld[selectedPerson]=Math.max(0,(next.unverifiedHeld[selectedPerson]||0)-records.length);const valid=C.normalize(next);checkpoint();state=valid;persist();renderHeld();renderJournal();$('eventIds').value='';}catch(err){$('journalError').textContent=err.message;}finally{button.disabled=false;}};
$('journalEntries').onclick=e=>{const b=e.target.closest('[data-remove]');if(!b||!editing)return;checkpoint();state.heldEvents=state.heldEvents.filter(e=>e.id!==b.dataset.remove);persist();renderHeld();renderJournal();toast('Запись убрана. Доступна отмена последнего изменения.');};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
$('undoBtn').onclick=()=>{if(!undoState)return;state=undoState;undoState=null;$('undoBtn').disabled=true;persist();render();if($('journalDialog').open)renderJournal();toast('Последнее изменение отменено');};
$('exportBtn').onclick=()=>download({...state},'sprint-backup-07-30-09-2026.json');
$('importBtn').onclick=()=>$('importFile').click();
$('importFile').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;const raw=JSON.parse(await file.text());const legacy=raw.schemaVersion!==2;if(legacy&&raw.period!=='07.09.2026-30.09.2026')throw Error('Для старого файла необходим период 07.09.2026-30.09.2026');pendingImport=C.normalize(raw,{legacy});const s=C.summary(pendingImport),current=C.summary(state);$('importSummary').textContent=`Назначено: ${current.assigned} → ${s.assigned}. Проведено: ${current.held} → ${s.held}. Начислено: ${rub(current.money)} → ${rub(s.money)}. Будет заменён весь локальный набор данных. Резервная копия сохранится автоматически.`;$('importDialog').showModal();}catch(err){toast(err.message);}finally{e.target.value='';}};
$('confirmImport').onclick=()=>{if(!pendingImport)return;checkpoint();try{localStorage.setItem(C.draftKey+'-before-import',JSON.stringify({state,baseAt}));}catch{}state=pendingImport;pendingImport=null;loadError=false;persist();render();$('importDialog').close();};
$('publishBtn').onclick=async()=>{if(loadError){toast('Сначала восстановите данные');return;}if(!await C.refresh()){toast('Не удалось проверить свежую версию сайта. Повторите после восстановления связи.');return;}if(Object.values(state.unverifiedHeld).some(n=>n>0)){toast('Сначала укажите даты старых проведённых встреч через журнал');return;}if(hasDraft&&baseAt!==published.updatedAt&&C.signature(state)!==C.signature(published)){toast('На сайте есть более новая версия. Скачайте резервную копию и согласуйте изменения перед публикацией.');return;}$('publishDialog').showModal();};
$('downloadPublic').onclick=()=>{const payload=C.normalize(state);payload.updatedAt=new Date().toISOString();download(payload,'state.json');};
$('refreshBtn').onclick=()=>C.refresh();
$('usePublished').onclick=()=>{checkpoint();state=JSON.parse(JSON.stringify(published));baseAt=published.updatedAt;loadError=false;persist();render();toast('Загружена опубликованная версия. Предыдущую можно вернуть кнопкой отмены.');};
C.watch((remote,status)=>{published=remote;$('syncStatus').textContent=status.message;$('syncStatus').classList.toggle('pending',!!status.error);if(!loadError&&status.lastSuccess&&(!hasDraft||C.signature(state)===C.signature(remote))){state=JSON.parse(JSON.stringify(remote));baseAt=remote.updatedAt;hasDraft=false;try{localStorage.setItem(C.draftKey,JSON.stringify({state,baseAt}));}catch{}if(status.changed)render();}draftStatus();});
render();
