// Public panel: published data only. Editing and payment updates happen through GitHub.
(()=>{
'use strict';
const C=window.Contest,people=C.people,milestones=C.milestones,days=Array.from({length:24},(_,i)=>i+7),depts=C.departments;
const mobile=matchMedia('(max-width:1000px)');let peoplePage=0;
const moneyFormatter=new Intl.NumberFormat('ru-RU');
const $=id=>document.getElementById(id),rub=n=>moneyFormatter.format(n)+' ₽',esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let state=C.cached(),view=location.hash==='#payments'?'payments':'assigned',query='',dept='all',startDay=7,endDay=innerWidth<1500?13:30,selectedPerson=null;
const reward=C.reward,nextReward=C.next,dayBonus=a=>a.reduce((s,n)=>s+Math.max(0,n-3)*1000,0),level=n=>n>=4?4:n,weekday=day=>['вс','пн','вт','ср','чт','пт','сб'][new Date(2026,8,day).getDay()];
function filtered(){return people.filter(p=>(dept==='all'||p.dept===dept)&&(!query||p.name.toLowerCase().includes(query.toLowerCase())));}
function visiblePeople(list=filtered()){const size=mobile.matches?10:list.length||1,pages=Math.max(1,Math.ceil(list.length/size));peoplePage=Math.min(peoplePage,pages-1);$('adminPager').hidden=!mobile.matches||pages===1;$('peoplePage').textContent=list.length?`${peoplePage*size+1}–${Math.min((peoplePage+1)*size,list.length)} из ${list.length}`:'Нет сотрудников';$('prevPeople').disabled=peoplePage===0;$('nextPeople').disabled=peoplePage>=pages-1;return list.slice(peoplePage*size,(peoplePage+1)*size);}
function dayContent(p,d,n){return `<span class="day-value">${n}</span>`;}
function mobileAssigned(list,visibleDays){return '<div class="mobile-assigned">'+list.map(p=>{const a=state.assigned[p.id];return `<section class="assigned-card" data-row="${p.id}"><h4>${esc(p.name)}</h4><small>${esc(p.dept)} · ${esc(p.role)}</small><div class="mobile-days">${visibleDays.map(d=>`<div class="mobile-day"><small>${d} ${weekday(d)}</small><div class="day-cell lv${level(a[d-1])}">${dayContent(p,d,a[d-1])}</div></div>`).join('')}</div><div class="card-summary"><div class="summary-col"><small>Всего встреч</small><b>${C.total(a)}</b></div><div class="summary-col"><small>Дней с целью</small><b>${a.slice(6).filter(n=>n>=3).length}</b></div><div class="money-col" data-amount="${C.bonus(a)}"><small>Начислено</small><b>${rub(C.bonus(a))}</b></div></div></section>`}).join('')+'</div>';}
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),5000);}
function updateStats(){const s=C.summary(state);$('statPeople').textContent=people.length;$('statAssigned').textContent=s.assigned;$('statHeld').textContent=s.held;$('statMoney').textContent=rub(s.money);$('statMoney').parentElement.dataset.amount=s.money;}
function dataStatus(){$('accessStatus').textContent='Только просмотр. Изменения вносит Илья Шуриков через ассистента.';$('updatedAt').textContent=state.updatedAt?'Данные: '+new Date(state.updatedAt).toLocaleString('ru-RU',{timeZone:'Europe/Moscow',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})+' МСК':'Результатов пока нет';}
function renderAssigned(){
 const list=visiblePeople(),visibleDays=days.filter(d=>d>=startDay&&d<=endDay);if(mobile.matches){$('assignedView').innerHTML=list.length?mobileAssigned(list,visibleDays):'<p class="empty">Сотрудники не найдены</p>';return;}let html='<table><thead><tr><th class="name-col">Сотрудник</th>';
 for(const d of visibleDays){const w=weekday(d);html+=`<th class="day-head ${w==='сб'||w==='вс'?'weekend':''}"><b>${d}</b><small>${w}</small></th>`;}
 html+='<th class="summary-col">Всего за конкурс</th><th class="summary-col">Дней с целью</th><th class="money-col">Начислено</th></tr></thead><tbody>';
 let last='';for(const p of list){if(p.dept!==last){last=p.dept;html+=`<tr class="group-row"><td colspan="${visibleDays.length+4}">${esc(last)}</td></tr>`;}const a=state.assigned[p.id];html+=`<tr data-row="${p.id}"><td class="name-col"><b>${esc(p.name)}</b><small>${esc(p.role)}</small></td>`;for(const d of visibleDays){const n=a[d-1];html+=`<td class="day-cell lv${level(n)}">${dayContent(p,d,n)}</td>`;}html+=`<td class="summary-col"><b>${C.total(a)}</b></td><td class="summary-col"><b>${a.slice(6).filter(n=>n>=3).length}</b></td><td class="money-col" data-amount="${C.bonus(a)}"><b>${rub(C.bonus(a))}</b></td></tr>`;}
 $('assignedView').innerHTML=list.length?html+'</tbody></table>':'<p class="empty">Сотрудники не найдены</p>';
}
function renderHeld(){let last='',html='<div class="prize-scale">'+milestones.map(m=>`<div class="prize-stop"><span>${m.n} ${m.n===3?'встречи':'встреч'}</span><b>${rub(m.p)}</b></div>`).join('')+'</div>';const list=visiblePeople();for(const p of list){if(p.dept!==last){last=p.dept;html+=`<div class="held-group">${esc(last)}</div>`;}const n=state.held[p.id],earned=reward(n),next=nextReward(n),target=next?next.n:milestones[milestones.length-1].n;html+=`<div class="held-row finish-row ${earned?'achieved':''} ${next?'':'complete'}"><div class="person"><b>${esc(p.name)}</b><small>${esc(p.role)}</small><button class="btn journal-btn" data-person="${p.id}">Журнал встреч</button></div><div class="held-fact"><b>${n}</b><small>проведено</small>${state.unverifiedHeld[p.id]?'<small class="pending">есть без дат</small>':''}</div><div class="journey"><div class="journey-meta"><b class="goal-label">${next?n+' из '+target+' встреч':'Все цели выполнены'}</b><span class="remaining">${next?'Ещё '+(target-n):'✓'}</span></div><div class="journey-bar" role="progressbar" aria-label="Прогресс конкурса по проведённым встречам" aria-valuemin="0" aria-valuemax="15" aria-valuenow="${Math.min(n,15)}"><div class="journey-fill" style="width:${C.progress(n)}%"></div>${milestones.map((m,i)=>`<span aria-hidden="true" class="journey-dot ${n>=m.n?'reached':next&&next.n===m.n?'current':''}" style="left:${(i+1)/milestones.length*100}%" title="${m.n} встреч: ${rub(m.p)}">${m.n}</span>`).join('')}</div><div class="journey-target">${next?'Цель: '+rub(next.p)+' · прибавка '+rub(next.p-earned):'Максимальная награда: '+rub(earned)}</div></div><div class="earned" data-amount="${earned}"><span>Заработано</span><b>${rub(earned)}</b></div></div>`;}$('heldView').innerHTML=list.length?html:'<p class="empty">Сотрудники не найдены</p>';}
function renderPayments(){
 const all=C.paymentRows(state),selected=new Set(filtered().map(p=>p.id)),rows=all.filter(r=>selected.has(r.personId)),sum=rows.reduce((t,r)=>{for(const k of ['amount','paid','due','queued','overpaid'])t[k]+=r[k];return t;},{amount:0,paid:0,due:0,queued:0,overpaid:0});
 const list=visiblePeople(filtered().filter(p=>rows.some(r=>r.personId===p.id)));
 $('paymentsView').innerHTML=`<div class="payment-totals"><div><small>Начислено</small><b>${rub(sum.amount)}</b></div><div class="pay-paid"><small>Выплатили</small><b>${rub(sum.paid)}</b></div><div class="pay-unpaid"><small>Осталось выплатить</small><b>${rub(sum.due)}</b></div><div class="pay-queued"><small>Поставили на выплату</small><b>${rub(sum.queued)}</b></div></div><p class="payment-note">Проведённые: первая награда и доплаты до следующей ступени. Суммы не дублируются. Статусы выплат доступны только для просмотра.</p>${sum.overpaid?'<p class="payment-warning">Выплаты превышают подтверждённые начисления на '+rub(sum.overpaid)+'. Проверьте изменённые встречи.</p>':''}`+list.map(p=>{
  const own=rows.filter(r=>r.personId===p.id),paid=own.reduce((n,r)=>n+r.paid,0),due=own.reduce((n,r)=>n+r.due,0);
  return `<details class="payment-person" ${due?'open':''}><summary><span><b>${esc(p.name)}</b><small>${esc(p.dept)}</small></span><span class="payment-person-amount">Выплатили ${rub(paid)}<strong class="${due?'text-unpaid':'text-paid'}">${due?'Осталось '+rub(due):'Всё выплачено'}</strong></span></summary><div class="payment-entries">${own.map(r=>{
   const status=r.overpaid?'review':r.paid>=r.amount&&r.amount>0?'paid':r.queued?'queued':r.paid?'partial':'unpaid',labels={review:'Проверить начисление',paid:'Выплатили',queued:'Поставили на выплату',partial:'Частично выплатили',unpaid:'Не выплатили'};
   return `<div class="payment-entry"><div><small>${r.kind==='assigned'?'Назначения':'Проведения'} · ${r.date?r.date.split('-').reverse().join('.'):'дата не подтверждена'}</small><b>${esc(r.label)}</b>${r.payment?'<small>Статус отмечен '+new Date(r.payment.markedAt).toLocaleDateString('ru-RU',{timeZone:'Europe/Moscow'})+'</small>':''}</div><div class="payment-entry-amount"><b>${rub(r.amount)}</b>${r.paid&&r.due?'<small>Выплачено '+rub(r.paid)+' · остаток '+rub(r.due)+'</small>':''}</div><div><span class="payment-status pay-${status}">${labels[status]}</span></div></div>`;
  }).join('')}</div></details>`;
 }).join('')+(list.length?'':'<p class="empty">На этой странице нет начисленных премий</p>');
}
function render(){for(const kind of ['assigned','held','payments']){$(kind+'View').hidden=view!==kind;if(view!==kind)$(kind+'View').replaceChildren();}if(view==='assigned')renderAssigned();else if(view==='held')renderHeld();else renderPayments();$('calendarRange').hidden=view!=='assigned';document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('boardTitle').textContent=view==='payments'?'Выплаты премий':view==='assigned'?'Назначения по дате назначения':'Проведённые за 7–30 сентября';$('boardSubtitle').textContent=view==='payments'?'По назначениям и проведениям отдельно':view==='assigned'?'Итоги справа всегда за весь конкурс':'Одна итоговая награда за достигнутую ступень';updateStats();dataStatus();}

function openJournal(id){selectedPerson=id;const p=people.find(p=>p.id===id);$('journalTitle').textContent=p.name+' · проведённые';renderJournal();$('journalDialog').showModal();}
function renderJournal(){const entries=state.heldEvents.filter(e=>e.personId===selectedPerson).sort((a,b)=>a.date.localeCompare(b.date));$('journalEntries').innerHTML=entries.length?entries.map(e=>`<div class="event-row"><span>${e.date.split('-').reverse().join('.')}</span><span>Запись ${e.id.slice(0,8)}</span></div>`).join(''):'<p>Записей пока нет.</p>'; }
$('deptFilter').innerHTML+=[...depts].map(d=>`<option value="${esc(d)}">${esc(d)}</option>`).join('');
document.querySelector('.tabs').onclick=e=>{const b=e.target.closest('.tab');if(b){view=b.dataset.view;history.replaceState(null,'',view==='payments'?'#payments':location.pathname+location.search);render();}};
$('search').oninput=e=>{query=e.target.value;peoplePage=0;clearTimeout(window.searchTimer);window.searchTimer=setTimeout(render,120);};
$('deptFilter').onchange=e=>{dept=e.target.value;peoplePage=0;render();};
$('prevPeople').onclick=()=>{peoplePage--;render();};$('nextPeople').onclick=()=>{peoplePage++;render();};$('adminMenu').open=!mobile.matches;mobile.addEventListener('change',()=>{$('adminMenu').open=!mobile.matches;peoplePage=0;render();});
$('calendarRange').value=startDay+':'+endDay;
$('calendarRange').onchange=e=>{[startDay,endDay]=e.target.value.split(':').map(Number);renderAssigned();};
$('heldView').onclick=e=>{const b=e.target.closest('[data-person]');if(b)openJournal(b.dataset.person);};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
$('refreshBtn').onclick=()=>C.refresh();
C.watch((remote,status)=>{$('syncStatus').textContent=status.message;$('syncStatus').classList.toggle('pending',!!status.error);if(status.changed){state=remote;render();if($('journalDialog').open)renderJournal();}else dataStatus();});
render();

})();
